version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes --requirepass Redis2019
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379:0:Redis2019
    ports:
    - "8082:8081"
